Update test.py
Since I tried to reproduce the testing result. It shows an error with '.module' - 
AttributeError: 'Model' object has no attribute 'module'. Did you mean: 'modules'?
Removing that part works fine.